// Code generated by sparkle.

package subgraph

//func (p *Price) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (m *MasterDeployer) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (w *WhitelistedFactory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (c *ConstantProductPoolFactory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (c *ConstantProductPool) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (c *ConcentratedLiquidityPoolFactory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (c *ConcentratedLiquidityPool) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (h *HybridPoolFactory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (h *HybridPool) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (i *IndexPoolFactory) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (i *IndexPool) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *Token) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (m *Mint) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (b *Burn) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (s *Swap) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

//func (t *Transaction) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}
