package subgraph

import (
	pbcodec "github.com/streamingfast/sparkle/pb/dfuse/ethereum/codec/v1"
)

func (s *Subgraph) HandleHybridPoolSyncEvent(ev *HybridPoolSyncEvent) error {
	panic("code skeleton generated by sparkle. implement me")
}
