package subgraph

import (
	pbcodec "github.com/streamingfast/sparkle/pb/dfuse/ethereum/codec/v1"
)

func (s *Subgraph) HandleConstantProductPoolApprovalEvent(ev *ConstantProductPoolApprovalEvent) error {
	panic("code skeleton generated by sparkle. implement me")
}
